# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# This line should NEVER be commented out when submitting to source-control. This is only for local development.
#org.gradle.java.home=C:\\Program Files\\Java\\jdk-21

# Fabric Properties
	# check these on https://fabricmc.net/use
	minecraft_version=26.2
	loader_version=0.19.3
	loom_version=1.17-SNAPSHOT

# Mod Properties
	mod_version = 7.1.0
	maven_group = com.prefab.fabric
	archives_base_name = prefab-fabric

# Dependencies
	# currently not on the main fabric site, check on the maven: https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api
	fabric_version=0.157.0+26.2
	mod_menu_version=20.0.1
	cloth_config_version=26.2.155
