name: Bug Report
description: Something doesn't work the way you expect or the game crashes/has an issue
title: "[Bug]: "
labels: [Bug]
body:
- type: markdown
  attributes:
    value: "# What version of Minecraft, what Mod Loader are you using (Fabric, NeoForge), and what Prefab version are you running?"
- type: input
  attributes:
    label: Minecraft Version
    placeholder: Minecraft Version
- type: input
  attributes:
    label: Mod Loader Name (Fabric, NeoForge)
    placeholder: REPLACE_ME
- type: input
  attributes:
    label: Mod Loader Version
    placeholder: REPLACE_ME Version
- type: input
  attributes:
    label: Prefab Version
    placeholder: Prefab Version
- type: markdown
  attributes:
    value: "# Please, provide as much detail as possible for the issue that you are running into. If possible post a log file to PasteBin or another similar site."
- type: textarea
  attributes:
    id: info
    label: Details
